/**
  * CalculatorView: Component representing a calculator via HTML+CSS
  * Only responsible for the view. Uses a calculator instance for actual processing
  */
class CalculatorView {
  constructor(context, calculator, prevValueScreen, operatorScreen, myScreen) {
    this.context = context;
    this.calculator = calculator;
    this.prevValueScreen;
    this.operatorScreen;
    this.myScreen;

    this.init();
  }

  /**
   * Initializes our component
   */
  init() {
    // Grab our screen elements
    this.prevValueScreen = this.context.getElementById('calculator__prev-value');
    this.operatorScreen = this.context.getElementById('calculator__operator');
    this.myScreen = this.context.getElementById('calculator__screen-value');

    // Init screen value
    this.refreshScreen();

    // Grab all our buttons
    const buttons = this.context.getElementsByClassName("calculator__button");
    for (let button of buttons) {
      // Receive click events
      button.addEventListener('click', evt => this.processClick(button, evt));
    }


    // Receive keyboard inputs
    this.context.addEventListener('keydown', evt => this.handleKeyboard(evt));
  }


  /**
   * Refresh our screen with current values
   */
  refreshScreen() {
    if (this.calculator.currentOperatorSymbol == null) {
      this.prevValueScreen.textContent = "";
      this.operatorScreen.textContent = "";
    } else {
      this.prevValueScreen.textContent = this.calculator.prevValue.toString();
      this.operatorScreen.textContent = CalculatorView.operationsSymbolsDict[this.calculator.currentOperatorSymbol];
    }

    this.myScreen.value = this.calculator.currentValueString;
  }

  /**
   * Process a click on one of our buttons. When called, 'this' is bound to the clicked button
   * 
   * @param {DOMButton} button  The button from which originated the click
   * @param {MouseEvent} event DOM event generated by the click
   */
  processClick(button, event) {
    const buttonValue = button.value;
    if (Calculator.isOperator(buttonValue)) {
      this.calculator.processOperator(buttonValue);
    } else {
      this.calculator.processNumber(buttonValue);
    }

    this.refreshScreen();
  }

  /**
   * Handles keypresses from user
   * @param {KeyboardEvent} event The input event
   */
  handleKeyboard(event) {
    let bHandled = false;
    if (CalculatorView.keysToOperatorsDict[event.key] !== undefined) {
      const operator = CalculatorView.keysToOperatorsDict[event.key];
      this.calculator.processOperator(operator);
      bHandled = true;
    } else if (Calculator.isNumber(event.key)) {
      this.calculator.processNumber(event.key);
      bHandled = true;
    }

    if (bHandled) {
      event.preventDefault();
      this.refreshScreen();
    }
  }
}

CalculatorView.operationsSymbolsDict = {
  "div": "/",
  "mul": "*",
  "sub": "-",
  "add": "+"
};

CalculatorView.keysToOperatorsDict = {
  "Escape": "clearElement",
  "Backspace": "back",
  "/": "div",
  "*": "mul",
  "-": "sub",
  "+": "add",
  ".": "dot",
  ",": "dot",
  "Enter": "equals",
  "=": "equals"
};
