// Grab our screen element
const myScreen = document.getElementById('calculator__screen-value');

// Init screen value
let currentValue = 0;
refreshScreen();

// Grab all our buttons
const buttons = document.getElementsByClassName("calculator__button");
for (let button of buttons) {
  button.addEventListener('click', processClick.bind(button));
}


/////////////////////////////
//  Helper functions
//

/**
 * Refresh our screen with current value
 */
function refreshScreen() {
  myScreen.value = currentValue;
}

/**
 * Process a click on one of our buttons. When called, 'this' is bound to the clicked button
 * 
 * @param {MouseEvent} event DOM event generated by the click
 */
function processClick(event) {
  console.log(event, this);
}